(PA-7089) Apply upstream rdoc fix for start_with?
Installing r10k was failing on ruby 2.7 due to our faulty rdoc patch

    /opt/puppetlabs/puppet/bin/gem install r10k
        ERROR:  While executing gem ... (NoMethodError)
        undefined method `start_with' for "RDoc::Markup::Document":String

Apply the upstream fix from ruby/rdoc@e21dfccb4a